# -*- mode: ruby -*-
# vi: set ft=ruby :

# Every Vagrant development environment requires a box. You can search for
# boxes at https://vagrantcloud.com/search.
BOX_IMAGE = "generic/ubuntu2004"

# Naming
MASTER_PREFIX = "k8s-master"
WORKER_PREFIX = "k8s-worker"
LB_NAME = "lb01"

# Networking
HOST_ONLY_NETWORK_NAME = "vboxnet0"
HOST_ONLY_NETWORK = "192.168.68"
LB_IP = 5
MASTER_IP_START_AT = 10
WORKER_IP_START_AT = 20
NETMARK = "24"

# Spec
MASTER_NODES = 3
MASTER_CPU = 1
MASTER_RAM = 2048

WORKER_NODES = 3
WORKER_CPU = 1
WORKER_RAM = 2048

LB_CPU = 1
LB_RAM = 2048


Vagrant.configure("2") do |config|
  # LB node
  config.vm.define LB_NAME do |l|
    l.vm.box = BOX_IMAGE
    l.vm.hostname = LB_NAME
    l.vm.network "private_network",
      name: HOST_ONLY_NETWORK_NAME,
      ip: "#{HOST_ONLY_NETWORK}.#{LB_IP}",
      netmask: NETMARK

    l.vm.provider "virtualbox" do |v|
      v.name = LB_NAME
      v.cpus = LB_CPU
      v.memory = LB_RAM
    end
  end

  # Master nodes
  (1..MASTER_NODES).each do |i|
    config.vm.define "#{MASTER_PREFIX}#{i}" do |m|
      m.vm.box = BOX_IMAGE
      m.vm.hostname = "#{MASTER_PREFIX}#{i}"
      m.vm.network "private_network",
        name: HOST_ONLY_NETWORK_NAME,
        ip: "#{HOST_ONLY_NETWORK}.#{MASTER_IP_START_AT + i}",
        netmask: NETMARK

      m.vm.provider "virtualbox" do |v|
        v.name = "#{MASTER_PREFIX}#{i}"
        v.cpus = MASTER_CPU
        v.memory = MASTER_RAM
      end
    end
  end
  
  # Worker nodes
  (1..WORKER_NODES).each do |i|
    config.vm.define "#{WORKER_PREFIX}#{i}" do |w|
      w.vm.box = BOX_IMAGE
      w.vm.hostname = "#{WORKER_PREFIX}#{i}"
      w.vm.network "private_network",
        name: HOST_ONLY_NETWORK_NAME,
        ip: "#{HOST_ONLY_NETWORK}.#{WORKER_IP_START_AT + i}",
        netmask: NETMARK

      w.vm.provider "virtualbox" do |v|
        v.name = "#{WORKER_PREFIX}#{i}"
        v.cpus = WORKER_CPU
        v.memory = WORKER_RAM
      end
    end
  end
end
